
namespace Game.Config
{
    public enum SoundType
    {
        DOUBLEP_SWORD, //aicharacter/_jojochan/thief/rai/animation/sonicassaultrapid1.ani
        R_DOUBLEP_KICK, //aicharacter/_jojochan/thief/rai/animation/sonicassaultrapid3.ani
        MF_NENTIGER, //aicharacter/atfighter/karsh/animation/nenflower.ani
        MF_NET_READY, //aicharacter/atfighter/randas/animation/throwweb.ani
        MNET_READY, //aicharacter/atfighter/roychan/animation/throwweb.ani
        SILVER_ATK3, //aicharacter/atfighter/tenero/animation/dashafterdashcombo2.ani
        MF_POWDER_CATCH, //aicharacter/atfighter/tenero/animation/grabexplosion.ani
        STRONG_LOWKICK, //aicharacter/atfighter/tenero/animation/limitpoint/kick.ani
        PR_4ATK0, //aicharacter/expc_sample/animation/attack.ani
        TF_CHAIN_3ATK, //aicharacter/fighter/sandman/animation/chainsawex4.ani
        R_GN_MULTIHEAD, //aicharacter/gunner/cypher_man/animation/multiheadshotextract.ani
        R_GN_MACH, //aicharacter/gunner/powerstation_gunner/animation/fastknee.ani
        PR_BIGPUNCH_GET, //aicharacter/priest/curse_priest/animation/bigbangpunchready.ani
        PR_APOCAL, //aicharacter/priest/ghostpriest/animation/apocalypse.ani
        PR_DCRASH, //aicharacter/priest/will/animation/divinecrush.ani
        SM_HOANYOUNG_02, //aicharacter/swordman/light_man/animation/waveeyespear.ani
        BIKER_EXP, //character/common/animation/booster_particle_0.ani
        BUFF_BURSTER, //character/common/animation/bustermode/buster_start_front_cross.ani
        TELEPORT_ACT_01, //character/common/animation/teleport/after/teleportend_circle01.ani
        TELEPORT_CAST, //character/common/animation/teleport/before/teleportstart_star.ani
        BIGPUNCH_3SWING_CRASH, //character/fighter/animation/blockbusterexfinish.ani
        HCOMBI_01, //character/fighter/animation/grabexplosionex.ani
        GROUNDKICK_READY, //character/fighter/animation/groundkickcharge.[pvp].ani
        GROUNDKICK, //character/fighter/animation/groundkickkick.ani
        DDASH, //character/fighter/animation/jumpsuplexlariat.[pvp].ani
        HOLD, //character/fighter/animation/legsuplexexthrow1.ani
        LIGHTNING_DASH_FIN, //character/fighter/animation/legsuplexexthrow2.ani
        FT_POSION_EXPLOSION, //character/fighter/animation/poisonmistexplosion.ani
        JUMPATK_FIN, //character/fighter/animation/stompfinish.ani
        FT_FIN_LOWKICK_FIN, //character/fighter/animation/strongestlowkick.ani
        FT_FIN_LOWKICK_GET, //character/fighter/animation/strongestlowkickready.ani
        FT_FIN_LOWKICK, //character/fighter/animation/strongestlowkickstamp.ani
        TFJUMP, //character/fighter/animation/trylegsuplexexsecond.ani
        FT_TYPHOON_FIN, //character/fighter/animation/typhoonfinish.ani
        FT_WC_SPIKE_FIN, //character/fighter/animation/wildcannonspikeexp.[pvp].ani
        FT_WC_SPIKE, //character/fighter/animation/wildcannonspikejump.ani
        MF_KMANG, //character/fighter/atanimation/108stairsexblow.ani
        MJUMP, //character/fighter/atanimation/108stairsexfinal.ani
        MF_1ATK, //character/fighter/atanimation/108stairsexkick.ani
        MF_2ATK, //character/fighter/atanimation/108stairsexpunch.ani
        MF_DASHATK, //character/fighter/atanimation/108stairsexthrow.ani
        MF_BELBOW_CATCH, //character/fighter/atanimation/108stairsextry.ani
        R_MKICK123, //character/fighter/atanimation/attack1.ani
        MF_3ATK, //character/fighter/atanimation/attack3.ani
        MKICK4, //character/fighter/atanimation/attack4.ani
        DBBLOW, //character/fighter/atanimation/blockbusterdouble.ani
        STONEJUMP, //character/fighter/atanimation/blockbusterjump.ani
        BECK_FIREBALL, //character/fighter/atanimation/blockbustershoot.ani
        BERIAS_WIND, //character/fighter/atanimation/chainkick.ani
        MF_CHULSAN, //character/fighter/atanimation/chargespearrecharge.ani
        MF_BOONG, //character/fighter/atanimation/chargespearrush.ani
        GIGONG_READY, //character/fighter/atanimation/closepunch.ani
        MVULCAN_READY, //character/fighter/atanimation/crashlowkick.ani
        R_KUNGFUMAN_KICK, //character/fighter/atanimation/crashlowkicksecond.ani
        MF_JUMP, //character/fighter/atanimation/crashrope.ani
        PUNCH3, //character/fighter/atanimation/dashafterdashcombo1.ani
        CBOONG_STONE_SPIN, //character/fighter/atanimation/destroyearthskydropfinish.ani
        AJUMP, //character/fighter/atanimation/destroyearthskydroponsky.ani
        CBOONG_CHAIN_THROW, //character/fighter/atanimation/destroyearthskydropstart.ani
        MF_POISON_THROW, //character/fighter/atanimation/enchantpoison.ani
        MSOONBO, //character/fighter/atanimation/fastdash.ani
        MFIRE_READY, //character/fighter/atanimation/flamelegscast.ani
        MDASH, //character/fighter/atanimation/glueyfruitthrow.ani
        BASIC_KICK_01, //character/fighter/atanimation/grabexplosion.ani
        GUNPOWDER_KICK, //character/fighter/atanimation/grabexplosionkick.ani
        MF_NEEDLE, //character/fighter/atanimation/hiddensting.ani
        DOUBLEP_KICK_01, //character/fighter/atanimation/holduphit.ani
        BELBOW_CATCH, //character/fighter/atanimation/holduphold.ani
        BELBOW_SIT, //character/fighter/atanimation/holduptry.ani
        MF_KMKANG, //character/fighter/atanimation/hurricanespear.ani
        LIGHTNING_DASH_01, //character/fighter/atanimation/jumpsuplex.ani
        MF_SPIRE, //character/fighter/atanimation/jumpsupleximpressholdkick.ani
        MJUNKSPIN, //character/fighter/atanimation/junkspinloop.[pvp].ani
        MF_ASTEINER, //character/fighter/atanimation/legsuplexholdkick.ani
        LIGHTNING_DASH_02, //character/fighter/atanimation/legsuplexthrow.ani
        MF_KCHOONG, //character/fighter/atanimation/lightningdragon.ani
        NENSU_CIRCLE, //character/fighter/atanimation/nenflower.ani
        NENSU_JUMP, //character/fighter/atanimation/nenflowerattack.ani
        MF_NENTIGER_FIN, //character/fighter/atanimation/nenflowerfinal.ani
        NENSU_BOARD, //character/fighter/atanimation/nenflowerready.ani
        NSPEAR_START, //character/fighter/atanimation/nenspear.ani
        SUPPER_01, //character/fighter/atanimation/punchafterreturn.ani
        MF_HONG, //character/fighter/atanimation/risingupperdash.ani
        CCRASH_MOVING, //character/fighter/atanimation/shouldercharge.[pvp].ani
        CSANKO_SHOCK, //character/fighter/atanimation/shouldercharge.ani
        NF_KWKANG, //character/fighter/atanimation/spiralcolumnex.ani
        NASUN_CHUL, //character/fighter/atanimation/spiralnenshoot.ani
        MNENTAN_READY, //character/fighter/atanimation/stompfinish.ani
        MF_SPX_FIN, //character/fighter/atanimation/suplexfinalattack.ani
        MF_ROPLING, //character/fighter/atanimation/throwenemythrow.ani
        HELLTER, //character/fighter/atanimation/throwsand.ani
        MNET_OUT, //character/fighter/atanimation/throwweb.ani
        NET_IN, //character/fighter/atanimation/throwwebdoublethrow.ani
        MF_SPIRE_FLY, //character/fighter/atanimation/tryjumpsuplex.ani
        SMASHER_CATCH, //character/fighter/atanimation/trysuplex.ani
        MF_ROPLING_CATCH, //character/fighter/atanimation/trythrowenemy.ani
        MF_SPX_3ATK, //character/fighter/atanimation/typhoonattack1.ani
        MF_SPX_2ATK, //character/fighter/atanimation/typhoonattack2.ani
        MF_SPX_1ATK, //character/fighter/atanimation/typhoonattack3.ani
        MF_HOSIN_1ATK, //character/fighter/atanimation/venommine.[pvp].ani
        VM_THROW, //character/fighter/atanimation/venommine.ani
        R_MLIGHTATK, //character/fighter/atanimation/whitetigerattack1.ani
        CASILLAS_FLASH, //character/fighter/atanimation/wildcannonspikecharge.ani
        WC_SPIKE_CRASH, //character/fighter/atanimation/wildcannonspikeexp.ani
        ITRENOG_LANDING, //character/fighter/effect/animation/at108stairsex/throw/floor_dodge_reverse.ani
        MVMINE_ELEC, //character/fighter/effect/animation/atvenommine/mine1_normal.[pvp].ani
        R_STRONG_LOWKICK_GET, //character/fighter/effect/animation/strongestlowkick/charge1.ani
        STRONG_LOWKICK_FLASH, //character/fighter/effect/animation/strongestlowkick/kick.ani
        TYPHOON_FIN_UP, //character/fighter/effect/animation/typhoon/finish1.ani
        ASTORM_DROP_02, //character/fighter/effect/animation/wildcannonspike/body_fire.ani
        GN_AIRRAID, //character/gunner/animation/airraid.[pvp].ani
        MANTLE_TIGHTEN, //character/gunner/animation/airraidex.ani
        R_GN_GUNGUARD, //character/gunner/animation/bulletguard.ani
        R_GN_C4, //character/gunner/animation/c4remoteready.ani
        GN_REVENGER, //character/gunner/animation/countershootready.ani
        R_GN_CROSS_SHOT, //character/gunner/animation/crossshoot.ani
        R_GN_DGUNHAWK_GUN, //character/gunner/animation/doublegunhawkcatch.ani
        GN_EXTRUDER, //character/gunner/animation/extruderready.[pvp].ani
        GN_EXTRUDER_FIRE, //character/gunner/animation/extrudershoot.[pvp].ani
        JACKSPIKE_SWING, //character/gunner/animation/multiheadshotexkick.ani
        TURTLE_SLUG, //character/gunner/animation/multiheadshotextract.[pvp].ani
        GN_MULTIHEAD_FIN, //character/gunner/animation/multiheadshotfinish.[pvp].ani
        GN_MULTIHEAD_READY, //character/gunner/animation/multiheadshotready.ani
        R_GN_PUNISHER_END, //character/gunner/animation/treadshoot.ani
        GN_PUNISHER, //character/gunner/animation/trytread.ani
        P_SSPIKE, //character/gunner/atanimation/airraidex.ani
        FG_ATRIGGER, //character/gunner/atanimation/ancienttriggerready.ani
        R_FG_GGUARD, //character/gunner/atanimation/bulletguard.ani
        R_FG_C4, //character/gunner/atanimation/c4remoteready.ani
        FG_REVENGER, //character/gunner/atanimation/countershootready.ani
        R_FG_CROSSM, //character/gunner/atanimation/crossshoot.ani
        R_FG_DGUNHAWK_GUN, //character/gunner/atanimation/doublegunhawkcatch.ani
        FG_EXTRUDER, //character/gunner/atanimation/extruderready.[pvp].ani
        FG_EXTRUDER_FIRE, //character/gunner/atanimation/extrudershoot.[pvp].ani
        R_FG_NSOBAT, //character/gunner/atanimation/fastknee.ani
        FG_G0, //character/gunner/atanimation/g0cast.ani
        R_FG_MULTIHEAD, //character/gunner/atanimation/multiheadshotexkick.ani
        FG_MULTIHEAD_FIN, //character/gunner/atanimation/multiheadshotfinish.[pvp].ani
        FG_MULTIHEAD_READY, //character/gunner/atanimation/multiheadshotready.ani
        R_FG_SPGUN, //character/gunner/atanimation/treadshoot.ani
        FG_SPGUN_SLIDING, //character/gunner/atanimation/trytread.ani
        FG_TWINGUN_SHOT_FIN, //character/gunner/atanimation/twingunbladeattackgunfinish.ani
        R_FG_TWINGUN_SWORD, //character/gunner/atanimation/twingunbladeattackknife1.ani
        FG_TWINGUN_SWORD_FIN, //character/gunner/atanimation/twingunbladeattackknife4.ani
        FG_TWINGUN_SHOT_DASH, //character/gunner/atanimation/twingunbladedashattackgun.ani
        FG_TWINGUN_SWORD_DASH, //character/gunner/atanimation/twingunbladedashattackknife.ani
        FG_TWINGUN_SHOWER, //character/gunner/atanimation/twingunbladefinishstart.ani
        FG_TWINGUN_SPIN, //character/gunner/atanimation/twingunbladegunhawk.ani
        FG_TWINGUN_SWORD_JUMP, //character/gunner/atanimation/twingunbladejumpattackknife.ani
        FG_TWINGUN, //character/gunner/atanimation/twingunbladestart.ani
        FG_TWINGUN_RKICK, //character/gunner/atanimation/twingunbladesumersault1.ani
        FG_TWINGUN_PULL_START, //character/gunner/atanimation/twingunbladethrowgun1.ani
        FG_TWINGUN_PULL, //character/gunner/atanimation/twingunbladethrowgun2.ani
        TWINGUN_SWORD_01, //character/gunner/effect/animation/attwingunblade/attackknife1-1.ani
        TWINGUN_SWORD_02, //character/gunner/effect/animation/attwingunblade/attackknife2-1.ani
        TWINGUN_SWORD_03, //character/gunner/effect/animation/attwingunblade/attackknife3-1.ani
        TWINGUN_SWORD_04, //character/gunner/effect/animation/attwingunblade/attackknife4-1.ani
        SCHUN_WAVE, //character/gunner/effect/animation/attwingunblade/dashattackknife1.ani
        TEANA_FLYATK, //character/gunner/effect/animation/attwingunblade/finishfinal1.ani
        R_TWINGUN_GUN, //character/gunner/effect/animation/attwingunblade/gunshoot.ani
        A_EYE_FLASH, //character/gunner/effect/animation/attwingunblade/start3.ani
        MUSSANG_SPIN, //character/gunner/effect/animation/attwingunblade/sumersault1.ani
        SWIND_01, //character/gunner/effect/animation/attwingunblade/throwgun1-1.ani
        GUNHAWK_SHOT, //character/gunner/effect/animation/doublegunhawk/throw.ani
        EXTRUDER_READY, //character/gunner/effect/animation/extruder/bodyready1.ani
        EXTRUDER_SHOT, //character/gunner/effect/animation/extruder/bodyshoot1.ani
        G0_READY, //character/gunner/effect/animation/g0/lockon1.ani
        GUNHAWK_GUN, //character/gunner/effect/animation/g0/lockonmark1.ani
        SPARROW_CREATE, //character/gunner/effect/animation/g0/lockonmarkappear1.ani
        SNIPING_READY, //character/gunner/effect/animation/nielsniping/radioappear1.ani
        BROOM_SPIN, //character/mage/animation/broomspinattack.ani
        WZ_FLUORE_COLLIDER, //character/mage/animation/fluorecollidercast.ani
        FCHASER_COM, //character/mage/animation/fusionchaser.ani
        WZ_FCRAFT_START, //character/mage/animation/fusioncraftcast.ani
        R_WZ_FCRAFT, //character/mage/animation/fusioncraftmake1.ani
        SILVER_SATK_ENERGY, //character/mage/animation/randompiercestrikefinishex.ani
        R_P_THUNDER_ATK, //character/mage/animation/randompiercestrikeloopex.ani
        WZ_TIMERBOMB, //character/mage/animation/timerbomb.ani
        R_CIRCLED_PUSH, //character/mage/animation/transformflapper.[pvp].ani
        JUDGMENT_SPEAR_01, //character/mage/animation/transformflapperex.[pvp].ani
        P_FLAPPER_HIT, //character/mage/animation/transformflapperex.ani
        MW_1ATK, //character/mage/atanimation/attack1.ani
        MW_2ATK, //character/mage/atanimation/attack2.ani
        MW_3ATK, //character/mage/atanimation/attack3.ani
        MW_4ATK, //character/mage/atanimation/attack4.ani
        ICEPIECE_LUMP, //character/mage/atanimation/bluedragonwill1.ani
        AQUARESS_ATK_01, //character/mage/atanimation/bluedragonwill2.ani
        WATERDRAGON_ATK, //character/mage/atanimation/bluedragonwill3.ani
        BARROW_MOVE, //character/mage/atanimation/brokenarrowdash1.ani
        BARROW_FIN, //character/mage/atanimation/brokenarrowdash2.ani
        CHAINLIGHT_ATK, //character/mage/atanimation/chainlightning.ani
        CHAINLIGHT_CAST, //character/mage/atanimation/chainlightningcast.ani
        CRYSTALATK_CAST, //character/mage/atanimation/crystalattack.ani
        DCHANGE_CAST, //character/mage/atanimation/darkchangeready.ani
        DCHANGE_CILCLE, //character/mage/atanimation/darkchangestart.ani
        MW_DASHATK, //character/mage/atanimation/dashattack.ani
        IMMORTAL_REVIVE, //character/mage/atanimation/diehard3.ani
        ERAIN_CIRCLE, //character/mage/atanimation/elementalrainchargeshoot.ani
        TELEPORT_ACT, //character/mage/atanimation/elementalrainjump.ani
        ERAIN_CAST, //character/mage/atanimation/elementalrainjumpstay.ani
        MW_ESTRIKE, //character/mage/atanimation/elementalstrikeex.ani
        ICESPEAR_CAST, //character/mage/atanimation/fallenblossoms1.ani
        ICESPEAR_ATK, //character/mage/atanimation/fallenblossoms2.ani
        ICESPEAR_FIN, //character/mage/atanimation/fallenblossoms3.ani
        FPILLAR_CAST, //character/mage/atanimation/firepillar1.ani
        FPILLAR_SHOT, //character/mage/atanimation/firepillar3.ani
        FIREROAD_01, //character/mage/atanimation/fireroadcast1.ani
        FIREROAD_02, //character/mage/atanimation/fireroadcast2.ani
        FLAMECILCLE_SPIN, //character/mage/atanimation/flamecircle1.ani
        FLAMECILCLE_ATK, //character/mage/atanimation/flamecircle3.ani
        ICEAREA_CAST, //character/mage/atanimation/frozenland1.ani
        ICEEARTH_WAVE, //character/mage/atanimation/frozenland2.ani
        ICEEARTH_EXP, //character/mage/atanimation/frozenland3.ani
        LAMPLIGHT_CAST, //character/mage/atanimation/holonglight.ani
        MW_ICERAIN, //character/mage/atanimation/icearea.ani
        ICEPIECE_CAST, //character/mage/atanimation/icechakram1.ani
        RAGEBLAST_READY, //character/mage/atanimation/icechakram2.ani
        RAGEBLAST_TAKE, //character/mage/atanimation/icechakram4.ani
        RAGEBLAST_THROW_01, //character/mage/atanimation/icechakram6.ani
        ICECRASH_BUMP, //character/mage/atanimation/icecrashend.ani
        ICECRASH_ATK, //character/mage/atanimation/icecrashstart.ani
        MW_SUIN_1ATK, //character/mage/atanimation/iceelementalattack1.[pvp].ani
        MW_SUIN_2ATK, //character/mage/atanimation/iceelementalattack2.[pvp].ani
        MW_SUIN_3ATK, //character/mage/atanimation/iceelementalattack3.ani
        ICEBLADE_CAST, //character/mage/atanimation/iceroad.ani
        MW_ICEBLADE_1ATK, //character/mage/atanimation/icesword.ani
        MW_JUMP, //character/mage/atanimation/jump.ani
        R_MW_JUMPATK, //character/mage/atanimation/jumpattack.ani
        MW_LIGHTWALL_READY, //character/mage/atanimation/lightningwall.ani
        MCANNON_CAST, //character/mage/atanimation/magiccannon4.ani
        ESHIELD_CAST, //character/mage/atanimation/magicshield.ani
        MW_PIECEICE, //character/mage/atanimation/pieceofice.ani
        PUSHOUT_02, //character/mage/atanimation/push.ani
        PUSHOUT_01, //character/mage/atanimation/pushgrab.ani
        KMYUNG_CAST, //character/mage/atanimation/resonance.ani
        SPINSPEAR_CAST, //character/mage/atanimation/turnwindmill1.ani
        SPINSPEAR_THROW, //character/mage/atanimation/turnwindmill2.ani
        WCANNON_CAST, //character/mage/atanimation/watercannon.ani
        MW_WINDSTRIKE, //character/mage/atanimation/windstrike.ani
        FIREHURRICANE_READY, //character/mage/creatoranimation/firehurricane.ani
        R_CASTING_CR, //character/mage/creatoranimation/firewall.ani
        R_ICESHIELD, //character/mage/creatoranimation/iceshield.ani
        MADO_FAILURE, //character/mage/effect/animation/familiar/flashfail.ani
        MADO_GREAT_SUCCESS, //character/mage/effect/animation/familiar/flashgreat1.ani
        MADO_SUCCESS, //character/mage/effect/animation/familiar/flashsuccess1.ani
        R_FCRAFT_HAMMER, //character/mage/effect/animation/fusioncraft/make1-1.ani
        COLLIDER_STEAM, //character/mage/effect/animation/megadrill/smoke2.ani
        WZ_SWING, //character/mage/effect/animation/swingex/dark_normal.ani
        P_MAGESWING_FIRE, //character/mage/effect/animation/swingex/fire_dodge.ani
        P_MAGESWING_LIGHT, //character/mage/effect/animation/swingex/light_dodge.ani
        MAGE_SWING, //character/mage/effect/animation/swingex/none_normal.ani
        P_MAGESWING_WATER, //character/mage/effect/animation/swingex/water_dodge.ani
        PR_MUSSANG_01, //character/priest/animation/atomicsmash.[pvp].ani
        PR_MUSSANG_FIN, //character/priest/animation/atomicsmash.ani
        PR_AVG1ATK, //character/priest/animation/avengerattack1.ani
        PR_AVG2ATK, //character/priest/animation/avengerattack2.ani
        PR_AVG3ATK, //character/priest/animation/avengerattack3.ani
        PR_AVG4ATK, //character/priest/animation/avengerattack4_rosary.ani
        DGUARDIAN_ATK_1, //character/priest/animation/avengerawakening/attack1.ani
        DGUARDIAN_ATK_2, //character/priest/animation/avengerawakening/attack2.ani
        DGUARDIAN_ATK_3, //character/priest/animation/avengerawakening/attack3.ani
        DGUARDIAN_ATK_4, //character/priest/animation/avengerawakening/attack3_ld.ani
        DGUARDIAN_CHOP_1, //character/priest/animation/avengerawakening/attack4.ani
        PR_DGUARDIAN_CHOP, //character/priest/animation/avengerawakening/attack5.ani
        PR_DGUARDIAN_DASH, //character/priest/animation/avengerawakening/dashattack.ani
        DGUARDIAN_DASH, //character/priest/animation/avengerawakening/dashattack_ld.ani
        GLARINE_ATK, //character/priest/animation/avengerawakening/pandemoniumstart.ani
        PR_DGUARDIAN_CHANGE, //character/priest/animation/awakening1.ani
        DGUARDIAN_CHANGE_1, //character/priest/animation/awakening2.ani
        DGUARDIAN_CHANGE_2, //character/priest/animation/awakening4.ani
        DGUARDIAN_BACK_1, //character/priest/animation/awakeningturnoff.ani
        DGUARDIAN_BACK_2, //character/priest/animation/awakeningturnoff2.ani
        PR_BIGPUNCH_02, //character/priest/animation/bigbangpunch1.ani
        PR_BIGPUNCH_DOWN, //character/priest/animation/bigbangpunch2.ani
        PR_BIGPUNCH_FIN, //character/priest/animation/bigbangpunch3.ani
        PR_BIGPUNCH_01, //character/priest/animation/bigbangpunchready.ani
        PR_DRAGONSPEAR, //character/priest/animation/bluedragon1.ani
        PR_DRAGONSPEAR_SHOT, //character/priest/animation/bluedragon3.ani
        PR_DWALL, //character/priest/animation/deflectwall.ani
        DISASTER_READY, //character/priest/animation/disaster1.ani
        DISASTER_JUMP, //character/priest/animation/disaster2.ani
        G0_LASER_EXP, //character/priest/animation/disaster4.ani
        EARTHQUAKE_START, //character/priest/animation/earthquake.ani
        EXECUTION_EXP_2, //character/priest/animation/execution/grabex.ani
        EXECUTION_PAUSE, //character/priest/animation/execution/last.ani
        EXECUTION_CRASH, //character/priest/animation/execution/turnover.ani
        PR_WEAPONATK_01, //character/priest/animation/exorcistattack1.ani
        PR_WEAPONATK_02, //character/priest/animation/exorcistattack2.ani
        PR_FMOVE, //character/priest/animation/fastmove1.ani
        FMOVE_SPIN, //character/priest/animation/fastmove2.ani
        FMOVE_STOP, //character/priest/animation/fastmove4.ani
        PR_JATK_01, //character/priest/animation/groundcrash.[pvp].ani
        NANK_ATK, //character/priest/animation/groundcrash.ani
        PR_PHAMMER, //character/priest/animation/hammerofcontrition.[pvp].ani
        PR_HCOMBI_RIGHT, //character/priest/animation/heavenlycombination.ani
        R_HCOMBI, //character/priest/animation/heavenlycombinationex.ani
        HEDGEHOG_START, //character/priest/animation/hedgehog.ani
        FASTCUT_SWISH, //character/priest/animation/highspeedslashattack1.ani
        FASTCUT_WHOOSH, //character/priest/animation/highspeedslashlast.ani
        PR_MJAP_UP, //character/priest/animation/machinegunjabappend.ani
        BIGPUNCH_12SWING, //character/priest/animation/machinegunjabexfinish.ani
        R_PR_SWIND, //character/priest/animation/machinegunjabexleft.ani
        R_SWIND, //character/priest/animation/machinegunjabexright.ani
        PR_MJAP_DOWN, //character/priest/animation/machinegunjabfinish.[pvp].ani
        PR_RIPPER_02, //character/priest/animation/pandemoniumstart.ani
        DARKPOWER_CAST, //character/priest/animation/powerofdarknessstart.ani
        PR_SPIN_FIN, //character/priest/animation/repeatedsmashexfinish.ani
        RIPPER_START, //character/priest/animation/ripper.ani
        PR_SWIND_PULL, //character/priest/animation/sidewindsecond.[pvp].ani
        PR_WSPEAR_GET, //character/priest/animation/spearofvictoryready.ani
        PR_WSPEAR_THROW, //character/priest/animation/spearofvictorythrow.ani
        PR_SCUTTER, //character/priest/animation/spincutter1.ani
        SCUTTER_SPIN, //character/priest/animation/spincutter2.ani
        SCUTTER_CATCH, //character/priest/animation/spincutter3.ani
        APOCAL_GET, //character/priest/effect/animation/apocalypse/cast1.ani
        MUSSANG_READY, //character/priest/effect/animation/atomicsmash/effect.ani
        BIGPUNCH_SWING_BACK, //character/priest/effect/animation/bigbangpunch/punch0.ani
        BIGPUNCH_3SWING, //character/priest/effect/animation/bigbangpunch/punch3.ani
        BIGPUNCH_READY, //character/priest/effect/animation/bigbangpunch/start1.ani
        DRAGONSPEAR_CREATE, //character/priest/effect/animation/bluedragon/change5.ani
        DRAGONSPEAR_START, //character/priest/effect/animation/bluedragon/dragongate.ani
        DRAGONSPEAR_FIRE, //character/priest/effect/animation/bluedragon/start1.ani
        DRAGONSPEAR_SPEAR, //character/priest/effect/animation/bluedragon/start3.ani
        HADOUKEN, //character/priest/effect/animation/cuttingdarkness/normalcut-dodge.ani
        STAR_ATK, //character/priest/effect/animation/galesmash/smash.ani
        PHAMMER_CREATE, //character/priest/effect/animation/hammerofcontrition/hammer1.ani
        HCOMBI_STRAIGHT, //character/priest/effect/animation/heavenlycombination/effect2.ani
        HCOMBI_EXP, //character/priest/effect/animation/heavenlycombination/effect3.ani
        R_MJAP, //character/priest/effect/animation/machinegunjab/jab.ani
        SWIND_02, //character/priest/effect/animation/sidewind/second.ani
        WSPEAR_CREATE_BIG, //character/priest/effect/animation/spearofvictory/charge3.ani
        WSPEAR_CREATE, //character/priest/effect/animation/spearofvictory/spearstart.ani
        SM_MUSSANG_START, //character/swordman/animation/blachecast.ani
        SM_MUSSANG_STRONG, //character/swordman/animation/blachesmash.ani
        SM_BOONGSAN, //character/swordman/animation/bloodswordcharge.[pvp].ani
        BLOODSWORD, //character/swordman/animation/bloodswordcharge.ani
        BLOODSWORD_READY, //character/swordman/animation/bloodswordmake.ani
        W_MOVING_ATK_FIN, //character/swordman/animation/chargecrashexupper.ani
        MOON_ATK_02, //character/swordman/animation/flowmindone.ani
        SM_GUE_ATK_02, //character/swordman/animation/flowmindoneadd.ani
        SM_GUARD, //character/swordman/animation/flowmindstart.ani
        SM_GUE_ATK_01, //character/swordman/animation/flowmindthreeattack.ani
        R_SM_JUMP_ATK, //character/swordman/animation/flowmindtwoattack1.ani
        SM_JUMP, //character/swordman/animation/flowmindtwojump.ani
        MENGRYOUNG_ATK, //character/swordman/animation/ghostsidewind.ani
        GORECROSS_ATK3, //character/swordman/animation/gorecross.ani
        SM_BLOOD_RAVE_ATK, //character/swordman/animation/hellbenterfinish.ani
        R_DRAWING_SWORD, //character/swordman/animation/momentaryslashex.ani
        SM_TOMBSTONE, //character/swordman/animation/tombstoneex.ani
        SM_CONGESTION, //character/swordman/animation/triplestab.ani
        R_SM_MENGRYONG, //character/swordman/animation/waveeyeclaw.ani
        DS_DARKSWORD, //character/swordman/dsanimation/bloodswordcharge.ani
        DARKSWORD_READY, //character/swordman/dsanimation/bloodswordmake.ani
        DARK_CRASHER, //character/swordman/dsanimation/chargecrashupper.ani
        DARK_SLASH, //character/swordman/dsanimation/darkwave.ani
        DS_BOONGSAN, //character/swordman/dsanimation/flowmindone.ani
        JAKYEOL_SWING, //character/swordman/dsanimation/flowmindoneadd.ani
        RYUSIM_READY, //character/swordman/dsanimation/flowmindstart.ani
        R_BRI_CUT, //character/swordman/dsanimation/flowmindtwoattack1.ani
        R_DS_ATK, //character/swordman/dsanimation/flowmindtwoattack2.ani
        R_DS_JUMP, //character/swordman/dsanimation/flowmindtwojump.ani
        WHIP_ATK, //character/swordman/dsanimation/ghostsidewind.ani
        HOP_SMASH, //character/swordman/dsanimation/hopsmash.ani
        DRAW_SWORD, //character/swordman/dsanimation/momentaryslash.ani
        R_DS_TRIPLE_SWORD, //character/swordman/dsanimation/triplestab.ani
        A_ICEWAVE, //character/swordman/dsanimation/waveeyeclaw.ani
        DS_BOODONG_EXPLOSION, //character/swordman/dsanimation/wavespinareabomb.ani
        B_START, //character/swordman/effect/animation/hellbenter/cast2.ani
        W_SPIRITS_FLASH, //character/swordman/effect/animation/hellbenter/completesword2.ani
        DRAWING_SWORD, //character/swordman/effect/animation/hellbenter/finish1.ani
        A_WING_CREATION, //character/swordman/effect/animation/waveeye/wing1.ani
        R_BASIC_KICK, //character/thief/animation/attack3.ani
        TF_GRUDGE, //character/thief/animation/blameofdead.ani
        GRUDGE, //character/thief/animation/blameofdeadex.ani
        R_TF_ATK12, //character/thief/animation/chainsawex1.ani
        P_CHAIN_FIN, //character/thief/animation/chainsawex4.ani
        R_TF_SHADOWCUT, //character/thief/animation/cutandgrabbackhit.ani
        SHADOWCUT_MOVE, //character/thief/animation/cutandgrabbackmove.ani
        R_TF_ERASER_FIN, //character/thief/animation/cutneckcut.ani
        TF_ERASER_ATK, //character/thief/animation/cutneckpoke1.ani
        TF_ERASER, //character/thief/animation/cutnecktry.ani
        R_GHOSTRUN, //character/thief/animation/darknail.ani
        TF_MYBLOOD, //character/thief/animation/darkritual.ani
        DARKSOUL_SHOT, //character/thief/animation/darksoul.ani
        R_TF_SLICER, //character/thief/animation/dashswingcut.ani
        TF_ASTRIKE_1ATK, //character/thief/animation/excelstrikehit1.ani
        TF_ASTRIKE_2ATK, //character/thief/animation/excelstrikehit2.ani
        TF_ASTRIKE_3ATK, //character/thief/animation/excelstrikehit3.ani
        TF_ASTRIKE, //character/thief/animation/excelstrikestart.[pvp].ani
        R_LIGHTNING_DASH, //character/thief/animation/excelstrikestart.ani
        FREET_FIREBALL_02, //character/thief/animation/flamecut.ani
        BENDYCUT_SWORD, //character/thief/animation/flashcut.[pvp].ani
        R_TF_SHININGCUT, //character/thief/animation/flashcut.ani
        UPPER_SLASH_02, //character/thief/animation/flashcutup.[pvp].ani
        TF_DIVINGARROW_FIN, //character/thief/animation/flyingkickfinish.ani
        TF_SQUIRREL_FIN, //character/thief/animation/flyingsquirrelhit.ani
        R_TF_SQUIRREL, //character/thief/animation/flyingsquirreltry.[pvp].ani
        R_TF_LIGHTNING_FIN, //character/thief/animation/inazmakickkick.ani
        R_TF_LIGHTNING_DASH, //character/thief/animation/inazmakickmove.ani
        TF_LIGHTNING, //character/thief/animation/inazmakicktry.[pvp].ani
        TFLANDING, //character/thief/animation/jump.ani
        TF_CHAIN_1ATK, //character/thief/animation/rorentocut1.[pvp].ani
        BENDYCUT_SPINSWORD, //character/thief/animation/rorentocut1.ani
        TF_CHAIN_2ATK, //character/thief/animation/rorentocut2.[pvp].ani
        R_TF_CHAIN_3ATK, //character/thief/animation/rorentocut3.[pvp].ani
        R_THIEF_THROW, //character/thief/animation/shuriken.ani
        TF_SSTEP, //character/thief/animation/sidestep.ani
        R_SILVER_SATK12, //character/thief/animation/silverstreamattack1.ani
        TF_SILVER_FIN, //character/thief/animation/silverstreamfinishslash.ani
        SILVER_ATK12, //character/thief/animation/silverstreamnormalattack1.ani
        BREAKING_RUSH, //character/thief/animation/skilldash.ani
        GHOSTRUN_HIT_01, //character/thief/animation/skintakeoff.ani
        TF_NICOLAS, //character/thief/animation/summonnicolas.ani
        R_TF_RISINGCUT, //character/thief/animation/uppercut.ani
        VERTICAL_CRASH, //character/thief/animation/verticalspiralcrash2.[pvp].ani
        CREATURE_LEVEL_UP, //common/commoneffect/animation/unlimitsuccess.ani
        RIDER_COUNT, //common/etc/animation/eventmap_countdown_3start.ani
        ICESPIRIT_CAST, //creature/aquajello/animation/aquajello_skill2_body.ani
        FIRESPIRIT_SKILL, //creature/automationcreature/animation/ignis_skill2_frontfire.ani
        FIRESPIRIT_CAST, //creature/automationcreature/animation/ignis_skill2_teleportstart.ani
        BAKALCRE_FIRE, //creature/bakal/animation/skill.ani
        PANDA_BUFF_START, //creature/bluepanda/animation/skill.ani
        PANDA_BAMBOO, //creature/bluepanda/animation/stay.ani
        BONNYBUNNY_THROW, //creature/bonnybunny/animation/tokki_skill1.ani
        BONNYBUNNY_JUMP, //creature/bonnybunny/animation/tokki_skill2_01.ani
        CRE_KKOPD_BUFF, //creature/camelcricket/skill1.ani
        CRE_KKOPD_OVER, //creature/camelcricket/skill2.ani
        SHELBYRED_SKILL_01, //creature/chn_shelby/shelbyblack/animation/shelbyblack_normal_skill_body.ani
        GBL_SUMMON_1ST, //creature/common/animation/transformeffect1.ani
        GBL_SUMMON_2ND, //creature/common/animation/transformeffect2.ani
        GBL_SUMMON_3RD, //creature/common/animation/transformeffect3.ani
        MON_CREATURE_CHANGE, //creature/common/animation/transformeffect4.ani
        HELLHOUND_CALL, //creature/hellhound/animation/hellhound_call.ani
        HELLHOUND_SKILL, //creature/hellhound/animation/hellhound_skill.ani
        HELLHOUND_TELE, //creature/hellhound/animation/hellhound_tele.ani
        CANFAIRY_CHANGE_RABBIT, //creature/launchergirl/animation/launchergirl_blue_call.ani
        CANFAIRY_LOAD, //creature/launchergirl/animation/launchergirl_blue_overskill.ani
        CANFAIRY_CHANGE_FAIRY, //creature/launchergirl/animation/launchergirl_red_call.ani
        TIGER_CRE_CHANGE_S, //creature/littletiger/strong/animation/goldtiger_change_baby.ani
        TIGER_CRE_CHANGE, //creature/littletiger/strong/animation/goldtiger_change_big.ani
        TIGER_CRE_STRETCH, //creature/littletiger/strong/animation/goldtiger_random1.ani
        TIGER_CRE_ATK, //creature/littletiger/swift/animation/silvertiger_change_big.ani
        TIGER_CRE_YAWN, //creature/littletiger/swift/animation/silvertiger_random1.ani
        FAGARU_FIREATK, //creature/petit_ashcore/skill/effect/petit_ashcore_effect_1_front.ani
        ASHCORE_CRE_LOOP, //creature/petit_ashcore/skill/effect/petit_ashcore_effect_2_front.ani
        ASHCORE_CRE_FIRE, //creature/petit_ashcore/skill/effect/petit_ashcore_effect_3_front.ani
        R_PETITBEBE_CALL, //creature/petit_bebe/animation/bebe_call.ani
        PETITBEBE_SKILL_01, //creature/petit_bebe/animation/bebe_skill_effect_b.ani
        PETITBEBE_SKILL_02, //creature/petit_bebe/animation/bebe_skill_effect_c1.ani
        PETITBEBE_SKILL_03, //creature/petit_bebe/animation/bebe_skill_effect_d.ani
        ITRENOG_CRE_LOOP, //creature/petit_itrenog/skill/effect/petit_itrenog_skill_loop_front.ani
        ITRENOG_CRE_SKILL, //creature/petit_itrenog/skill/effect/petit_itrenog_skill_start_front.ani
        NAGOR_CRE_LOOP, //creature/petit_nagor/skill/effect/petit_nagor_skill_loop_normal.ani
        NAGOR_CRE_SKILL, //creature/petit_nagor/skill/effect/petit_nagor_skill_start_normal.ani
        NMAUG_ENERGYBOX, //creature/petit_nemaug/skill/effect/petit_nemaug_effect_01.ani
        NMAUG_CRE_LOOP, //creature/petit_nemaug/skill/effect/petit_nemaug_effect_02.ani
        NMAUG_CRE_FIN, //creature/petit_nemaug/skill/effect/petit_nemaug_effect_03.ani
        PINO_CALL_03, //creature/pinocchia/animation/pinocchia_call_.ani
        PINO_GET, //creature/pinocchia/animation/pinocchia_exp_.ani
        PINO_STANDBY_03, //creature/pinocchia/animation/pinocchia_random.ani
        PINO_SKILL_03, //creature/pinocchia/animation/pinocchia_skill(a)_.ani
        PINO_SKILL_02, //creature/pinocchia/animation/pinocchia_skill(b)_body.ani
        PINO_CALL_02, //creature/pinocchio/animation/pinocchio_call_.ani
        PINO_STANDBY_02, //creature/pinocchio/animation/pinocchio_random.ani
        PINO_SKILL_01, //creature/pinocchio/animation/pinocchio_skill(b)_body.ani
        R_PRINCESSPETIT_CALL, //creature/princess_petit/animation/princess_call.ani
        PRINCESSPETIT_SKILL_01, //creature/princess_petit/animation/princess_skill_eff_a.ani
        PRINCESSPETIT_SKILL_02, //creature/princess_petit/animation/princess_skill_eff_c.ani
        THUNDERC_ATK_1, //creature/psy/animation/psy_skill1.ani
        PSY_PANG, //creature/psy/animation/psy_skill2.ani
        MONGSIL_CALL, //creature/rat_female/animation/response.ani
        BANGSIL_FOOD, //creature/rat_female/animation/skill.ani
        BANGSIL_DRINK, //creature/rat_female/animation/speedup.ani
        BANGSIL_CALL, //creature/rat_male/animation/response.ani
        BANGSIL_EAT, //creature/rat_male/animation/skill.ani
        PANDA_BUFF_RED, //creature/redpanda/animation/skill.ani
        REVA_PR_HAMMER, //creature/reva/crusader/skill.ani
        REVA_TF_NICOL, //creature/reva/necro/t_call_effect1.ani
        SWEETCANDYBAR_DISAPPEARANCE, //creature/reva/necro/t_call_effect2n.ani
        REVA_TF_SOUL, //creature/reva/necro/t_effect7_firen.ani
        SWEETCANDYBAR_CREATE, //creature/reva/necro/t_skill.ani
        NEN_DRAGONATK_SHOT, //creature/reva/nenma/skill.ani
        BOWGUN_GRAB, //creature/reva/ranger/skill.ani
        ASUNA_CRE_CALL, //creature/sao/asuna/animation/asuna_call_normal.ani
        ASUNA_CRE_LOOP_02, //creature/sao/asuna/animation/asuna_random(stand01).ani
        ASUNA_CRE_LOOP_04, //creature/sao/asuna/animation/asuna_random(stand03).ani
        ASUNA_CRE_LOOP_05, //creature/sao/asuna/animation/asuna_random(stand04).ani
        ASUNA_CRE_LOOP_01, //creature/sao/asuna/animation/asuna_random_normal.ani
        ASUNA_CRE_SKILL_01, //creature/sao/asuna/animation/asuna_skill_normal.ani
        RIZBET_CRE_SKILL_05, //creature/sao/riz/animation/riz_effect_normal_no(cha).ani
        RIZBET_CRE_SKILL_01, //creature/sao/riz/animation/riz_effect_normal_ok(cha).ani
        RIZBET_CRE_SKILL_07, //creature/sao/riz/animation/riz_effect_rare_no(cha).ani
        RIZBET_CRE_SKILL_03, //creature/sao/riz/animation/riz_effect_rare_ok(cha).ani
        RIFA_CRE_CALL, //creature/sao/suguha/animation/call.ani
        RIFA_CRE_LOOP_03, //creature/sao/suguha/animation/random.ani
        RIFA_CRE_LOOP_01, //creature/sao/suguha/animation/random01.ani
        R_50CALIBERA, //creature/sdcharacter/atgunner/fg_skill.ani
        REVA_PR_SWING, //creature/sdcharacter/priest/c_prist_skill.ani
        ACIDCLOUD_CREATE, //creature/sdcharacter/thief/c_call_effect2n.ani
        FG_MROSE_01, //creature/sdcharacterkr/atgunner/animation/fg_call.ani
        MW_BARROW_FIN, //creature/sdcharacterkr/atmage/animation/skill_mage_man_body.ani
        CR_WILL, //creature/sdcharacterkr/creator/animation/skill_sd_creator_creature.ani
        SHOCK_WAVE_ELEC, //creature/sdcharacterkr/darkknight/animation/skill_sd_darkknight_creature.ani
        FT_NENKA, //creature/sdcharacterkr/fighter/animation/c_f_fighter_random.ani
        GN_DMG_04, //creature/sdcharacterkr/gunner/animation/c_gunner_m_random.ani
        WZ_WALK_01, //creature/sdcharacterkr/mage/animation/c_mage_call.ani
        PR_DEVIL, //creature/sdcharacterkr/priest/animation/c_prist_call.ani
        TF_NICOLAS_OBEY, //creature/sdcharacterkr/thief/animation/c_thief_skill.ani
        RUDOLF_STAR, //creature/sledgerudolph/animation/blue_buff.ani
        RUDOLF_DASH, //creature/sledgerudolph/animation/blue_overskill.ani
        RUDOLF_SPIN, //creature/sledgerudolph/animation/blue_skill.ani
        RUDOLF_THROW, //creature/sledgerudolph/animation/red_skill.ani
        YOU_WIN_LOSE, //dungeon/event/bluemarble/title/eventmap_countdown_ready.ani
        CLICK_BUTTON4, //map/suspiciousvillage/animation/count9.ani
        MUSSANG_FLASH, //monster/act8/blackscalemoussambani/animation/effect.ani
        FREET_BITE, //monster/babydragon/babydragonanimation/attackbite.ani
        R_BIRD_CRY_E, //monster/babydragon/babydragonanimation/attackfireball.ani
        THROW_RAT, //monster/babydragon/babydragonanimation/attacknearbite.ani
        R_BIRD_CRY_D, //monster/babydragon/babydragonanimation/damage1.ani
        FREET_FIREBALL_01, //monster/babydragon/babydragonanimation/effect_serfire1_ldodge.ani
        CASILLAS_SWORD_PUT, //monster/casillas/animation/moveslash/bladein.ani
        CASILLAS_ATK, //monster/casillas/animation/moveslashafter.ani
        KEIGA_ATK, //monster/casillas/animation/moveslashmove.ani
        R_TSLASH, //monster/casillas/animation/slash/slash1-1.ani
        UPPER_SLASH_01, //monster/casillas/animation/slash/slash2-1.ani
        AUPPER_SWING, //monster/characterstatue/priestanimation/attack1.ani
        ATK_DARKLIGHTNING, //monster/characterstatue/swordmananimation/attack.ani
        DRGCANNON_READY, //monster/event/bluemarble/battlingram/battlingramani/attack.ani
        MUSSANG_SWING, //monster/event/bluemarble/blackscalemoussambani/animation/effect.ani
        MSKIN_DISA, //monster/fighter/animation/atillusionbomb/illusionbombdestroyeffect.ani
        NENWHA_DISAPPEAR, //monster/fighter/animation/nenflower/disappear2.ani
        BIGGOLEM_ATK_02, //monster/new_golem/animation_platany/attack.ani
        AQUARESS_DISAPPEAR, //monster/newmonsters/gbl/acidra/animation/die.ani
        NICOLAS_ZOMBIE, //monster/newmonsters/thief/nicolas/animation/casting1.ani
        NICOLAS_DARKWAVE, //monster/newmonsters/thief/nicolas/animation/casting2.[pvp].ani
        NI_DARKWAVE, //monster/newmonsters/thief/nicolas/animation/casting2.ani
        NICOLAS_ARACLOSO, //monster/newmonsters/thief/nicolas/animation/casting3.ani
        NICOLAS_BLACKWEB, //monster/newmonsters/thief/nicolas/animation/casting4.ani
        P_NI_DARKWAVE_START, //monster/newmonsters/thief/nicolas/animation/casting5.[pvp].ani
        P_NI_DARKWAVE, //monster/newmonsters/thief/nicolas/animation/casting5.ani
        NI_SUMMON, //monster/newmonsters/thief/nicolas/animation/comein.ani
        R_NICOLAS_DMG, //monster/newmonsters/thief/nicolas/animation/damage1.ani
        NICOLAS_SPIDER, //monster/newmonsters/thief/nicolas/animation/throw.ani
        TYPHOON_FIN_CRASH, //monster/newmonsters/timegate/beginning/baby_hisma/animation/hisma_finish.ani
        DRAGONSPEAR_CRASH, //monster/newmonsters/timegate/black_church/nillbass/animation/casting/explight1.ani
        JUDGMENT_FIN, //monster/newmonsters/timegate/black_church/nillbass/animation/gound/exp1.ani
        R_SQUARESWDA, //monster/soldier/animationaxeexpeller/attack.ani
        SQUARESWDB, //monster/soldier/animationaxionexpeller/attack.ani
        SQUARESWDC_01, //monster/soldier/animationaxionexpeller/pierce.ani
        P_SANDOR_ENERGY, //monster/soldier/animationsandorexpellerex/chargepierce.ani
        ECHEVERRA_READY, //monster/spikeking/animation_spikeking/attacklaser.ani
        ECHEVERRA_LASER, //monster/spikeking/animation_spikeking/effect_laser.ani
        KALA_ATK_12, //monster/spirit/magedarkhigheranimation/attack1.ani
        KALA_ATK_3, //monster/spirit/magedarkhigheranimation/attack2.ani
        DMURKER_DISAPPEAR_01, //monster/spirit/magedarkhigheranimation/die.ani
        OUTRAGE_SWING, //monster/spirit/magefirehigheranimation/attack1.ani
        FHULK_FLASH, //monster/spirit/magefirehigheranimation/attack3effect.ani
        FHULK_SELF, //monster/spirit/magefirehigheranimation/attack3effectboom.ani
        FHULK_DISAPPEAR, //monster/spirit/magefirehigheranimation/die.ani
        GLARINE_DISAPPEAR, //monster/spirit/magelighthigheranimation/die.ani
        AQUARESS_ICE, //monster/spirit/magewaterhigheranimation/attack1.ani
        AQUARESS_ICE_READY, //monster/spirit/magewaterhigheranimation/attack3.ani
        ASTORM_EXP_WATER, //monster/spirit/magewaterhigheranimation/die.ani
        ZGM_ATK, //monster/starfish/devanimation/doinglandrolling.ani
        ZGM_SPRING, //monster/starfish/devanimation/trybite.ani
        FIRE_EXPLOSION_CREATE, //passiveobject/actionobject/common/animation/tempester/expairdodge.ani
        SAJAHU_SPREAD, //passiveobject/actionobject/map/risk_dungeon/ghosttrain/animation/crashfloor.ani
        JEWEL_HIT, //passiveobject/actionobject/monster/agamemnon/animation/angelspear/land.ani
        ARM_UNDERLAND, //passiveobject/actionobject/monster/agamemnon/animation/angelspear/landfull.ani
        R_JUDGMENT_SPEAR, //passiveobject/actionobject/monster/agamemnon/animation/cast/star1.ani
        ASTORM_EXP_FIRE, //passiveobject/actionobject/monster/assaultdog/animation/missileexpairdodge.ani
        EXTRUDER_HIT, //passiveobject/actionobject/monster/biggun/animation/exp1.ani
        JUDGMENT_ANGEL, //passiveobject/actionobject/monster/dimensiongate/blackearth/michaela/animation/judgement/angel1.ani
        JUDGMENT_CIRCLE, //passiveobject/actionobject/monster/dimensiongate/blackearth/michaela/animation/judgement/floor1.ani
        NI_DARKWAVE_EXP, //passiveobject/actionobject/monster/dimensiongate/cosmofiend/insent/animation/darkexplosion.ani
        FLASHMINE_READY, //passiveobject/actionobject/monster/goblinunderminer/animation/startmine.ani
        P_SAYA_ICE, //passiveobject/actionobject/monster/masaccio/animation/start.ani
        NI_SPIDER, //passiveobject/actionobject/monster/nicolas/animation/throw_object.ani
        NI_ZOMBIE, //passiveobject/actionobject/monster/nicolas/animation/zombiesummon/ballwork.ani
        ECHEVERRA_ARM_ATK, //passiveobject/actionobject/monster/shonan/animation/biwoong_slasheffect_dodge.ani
        EARTHQUAKE_ROCKWAVE, //passiveobject/actionobject/monster/shonan/jojo/animation/base.ani
        ICESPIRIT_SKILL, //passiveobject/actionobject/monster/timegate/animation/aquajello_skill2_icepole1.ani
        ICESPIRIT_FIN, //passiveobject/actionobject/monster/timegate/animation/aquajello_skill2_icepole2.ani
        R_ICEAREA_CRASH, //passiveobject/actionobject/monster/timegate/beginning/animation/break_exp.ani
        P_VIPER_LASER, //passiveobject/actionobject/monster/timegate/beginning/animation/lasertile.ani
        ATRIGGER_FIN, //passiveobject/actionobject/monster/timegate/topsecretarea/hgoblin/animation/disappear1.ani
        B_FIRE_EXPLOSION_READY, //passiveobject/actionobject/spc/_avengers/overkill2/animation/appear1.ani
        B_FIRE_EXPLOSION, //passiveobject/actionobject/spc/_avengers/overkill2/animation/appear5.ani
        ASTORM_HIT_FIRE, //passiveobject/actionobject/spc/_avengers/overkill2/animation/disappear2.ani
        FIRE_BOMB, //passiveobject/actionobject/spc/_goblingenerator/animation/5cannon.ani
        SNOW_DROP, //passiveobject/actionobject/trap/animation/snowballdestroy.ani
        NENSU_CRASH, //passiveobject/character/fighter/animation/at108stairsex/floor_normal.ani
        CRAZYWHIP_LAND, //passiveobject/character/fighter/animation/atcrashrope/floor_normal1.ani
        MPOISON_EXP, //passiveobject/character/fighter/animation/atenchantpoison/atpoisonflaskexplosion.ani
        PFRUIT_EXP, //passiveobject/character/fighter/animation/atglueyfruit/atexplosionbase.ani
        R_PUNCH12_HIT, //passiveobject/character/fighter/animation/atholdup/holdupsub.ani
        ASTORM_EXP_LIGHT, //passiveobject/character/fighter/animation/atnenspear/nenspearexplosionbase.ani
        NHWAN_LIGHTNING, //passiveobject/character/fighter/animation/atspiralcolumnex/target_dodge.ani
        HANNOM_HIT, //passiveobject/character/fighter/animation/attyphoon/attyphoonkickexplosion.ani
        WC_SPIKE_STONE, //passiveobject/character/fighter/animation/atwildcannonspikesub/stone_big.ani
        FLAMES_EXPLOSION, //passiveobject/character/fighter/animation/wildcannonspike/expstonebreak.ani
        BOMB_EXPLOSION, //passiveobject/character/fighter/animation/wildcannonspike/sub1.ani
        ATRIGGER_READY, //passiveobject/character/gunner/animation/ancienttrigger/body3.ani
        FLASHMINE_UP, //passiveobject/character/gunner/animation/flashmine/expbody.ani
        G0_ROBOT, //passiveobject/character/gunner/animation/g0/appear1.ani
        G0_ROBOT_FIN, //passiveobject/character/gunner/animation/g0/appearfinish4.ani
        SPARROW_FACTORY, //passiveobject/character/gunner/animation/sparrowfactory/appeareffect.ani
        BOMB_02, //passiveobject/character/gunner/animation/stingerex/expfloornormal.ani
        ANTIGRAVITY_START, //passiveobject/character/mage/animation/antigravity/magiccircle.ani
        ANTIGRAVITY_STEAM, //passiveobject/character/mage/animation/antigravity/smoke1.ani
        DMANTLE_CAST, //passiveobject/character/mage/animation/atdarknessmantle/01/00_ground_light_dodge_50.ani
        DMANTLE_BREAK, //passiveobject/character/mage/animation/atdarknessmantle/crack/08_crack_back_normal_50.ani
        DARKPOWER_EXP, //passiveobject/character/mage/animation/atdarknessmantle/exp/10_exp_splinter_normal.ani
        DMANTLE_CIRCLE, //passiveobject/character/mage/animation/atdarknessmantle/suck/07_absorb_normal_50r.ani
        ERAIN_EXP, //passiveobject/character/mage/animation/atelementalrain/exp/17_end_normal.ani
        R_ICEAREA_ICE, //passiveobject/character/mage/animation/aticeareaicerain/01_icebit_normal.ani
        RAGEBLAST_EXP, //passiveobject/character/mage/animation/aticechakram/last/explosion/explosionbase.ani
        ICEMAN_LUMP, //passiveobject/character/mage/animation/aticeman/02_pole/pole_base.ani
        ICECRASH_LUMP, //passiveobject/character/mage/animation/aticeorbex/1_ready/03_icemarble_normal_2.ani
        LIGHTWALL_CAST, //passiveobject/character/mage/animation/atlightningwall/createlightningwallbase.ani
        R_FIREWALL, //passiveobject/character/mage/animation/creatorfirewall/01_firewall.ani
        ICEPLATE_FALL, //passiveobject/character/mage/animation/creatoriceplate/iceplate_ice_plate.ani
        R_WOODFENCE, //passiveobject/character/mage/animation/creatorwoodfence/woodfence_wood.ani
        FANTOM_EXP, //passiveobject/character/mage/animation/flamevolcanovoid/lastboom.ani
        FLAMES_FIRECIRCLE, //passiveobject/character/mage/animation/flamevolcanovoid/start.ani
        SUMMON_EQUIPMENT, //passiveobject/character/mage/animation/fluorecollider/create_body.ani
        FCRAFT_START, //passiveobject/character/mage/animation/fluorerasa/appear1.ani
        FCRAFT_FROST, //passiveobject/character/mage/animation/frostspin/appear.ani
        R_FCRAFT_FROST_ATK, //passiveobject/character/mage/animation/frostspin/object1-1.ani
        FCHASER_DIS, //passiveobject/character/mage/animation/fusionchaser/dl.ani
        R_WZ_FH_FURNACE_PUSH, //passiveobject/character/mage/animation/heatingfurnace/dust.ani
        HFURNACE_PUMP, //passiveobject/character/mage/animation/heatingfurnace/foot_n_loop.ani
        FCRAFT_FURNACE, //passiveobject/character/mage/animation/lanternfactory/appear.ani
        FCRAFT_PLUTO, //passiveobject/character/mage/animation/plutopunch/appear.ani
        FCRAFT_PLUTO_PUNCH, //passiveobject/character/mage/animation/plutopunch/attack1.ani
        DRAGONSPEAR_SHOT, //passiveobject/character/priest/animation/bluedragontotem/totem1.ani
        DGUARDIAN_CHOP_2, //passiveobject/character/priest/animation/devilstrike/attack2/2_shadow_normal.ani
        DCRASH_CRASH, //passiveobject/character/priest/animation/divinecrush/crush.ani
        AUPPER_CRASH, //passiveobject/character/priest/animation/groundcrash/oxcrash.ani
        CROSSCRASH_CRASH, //passiveobject/character/priest/animation/hotcross/crossparticle.ani
        JUDGMENT_ANGEL_SPEAR, //passiveobject/character/priest/animation/judgement/angel1.ani
        KALA_SUMMON, //passiveobject/character/priest/animation/pandemoniumex/pandemoniumexnormal.ani
        DARKPOWER_STINGER, //passiveobject/character/priest/animation/powerofdarkness/arrow.ani
        RIPPER_EXP, //passiveobject/character/priest/animation/ripperexplosion/base.ani
        SCHUN_CIRCLE, //passiveobject/character/priest/animation/risingarea/circle.[pvp].ani
        SHIKIGAMI_BIGBIRD, //passiveobject/character/priest/animation/shikigami/expbird1.ani
        SHIKIGAMI_CIRCLE, //passiveobject/character/priest/animation/shikigami/square1.ani
        JUJAK_CIRCLE, //passiveobject/character/priest/animation/vermilionbirdtalisman/talisman.ani
        S_BLASHU_ENTER, //passiveobject/character/swordman/animation/blache/appearlight.ani
        S_BLASHU_SCREAM, //passiveobject/character/swordman/animation/blache/body1.ani
        DARK_EXPLOSION, //passiveobject/character/swordman/animation/blastblood1_ds.ani
        P_BLOODEXP, //passiveobject/character/swordman/animation/blastbloodex/ex_blood1.ani
        P_BLOODR_FIRE, //passiveobject/character/swordman/animation/bloodswordexplosion/exp.ani
        DARKSWORD_EXP, //passiveobject/character/swordman/animation/bloodswordexplosion_ds/exp.ani
        W_WEAPON_DRIVE, //passiveobject/character/swordman/animation/hundredswordhit.ani
        P_TOMBSTONE_CIRCLE, //passiveobject/character/swordman/animation/tombstoneex/circle.ani
        BIGGOLEM_ATK_01, //passiveobject/character/swordman/animation/tombstoneex/start.ani
        P_TOMBSTONE_EXP, //passiveobject/character/swordman/animation/tombstoneexexplosion/explosion.ani
        A_WHEEL_CREATION, //passiveobject/character/swordman/animation/waveeye/wheelappear.ani
        BAL_AMBITION, //passiveobject/character/thief/animation/ambitionofballacre/hand_dodge1.ani
        BAL_AMBITION_FIN, //passiveobject/character/thief/animation/ambitionofballacre/hand_grab_dodge.ani
        BAL_GUILLOTINE_SWORD, //passiveobject/character/thief/animation/ballacre/attack_cast_guillotine_finish.[pvp].ani
        NANK_CRASH_FIN, //passiveobject/character/thief/animation/ballacre/attack_cast_guillotine_finish.ani
        PHAMMER_SWING, //passiveobject/character/thief/animation/ballacre/attack_cast_guillotine_start.[pvp].ani
        BALAC_ATK_HAND, //passiveobject/character/thief/animation/ballacre/attack_hand_pierce.[pvp].ani
        BALAC_ATK_SWORD, //passiveobject/character/thief/animation/ballacre/attack_swing_down.[pvp].ani
        BALAC_ATK_CONTINUE, //passiveobject/character/thief/animation/ballacre/attack_swing_loop.[pvp].ani
        ASTORM_EXP_DARK, //passiveobject/character/thief/animation/darklure/bead_exp_dodge.ani
        DSTRAIGHT_HIT, //passiveobject/character/thief/animation/flyingkickedbottom.ani
        SHELBYRED_SKILL_02_1, //passiveobject/creature/chn_shelby/shelbyblack/animation/09_shelbyblack_overskill_body.ani
        SHELBYRED_SKILL_02_2, //passiveobject/creature/chn_shelby/shelbyblue/animation/09_shelbyblue_overskill_body.ani
        SHELBYRED_SKILL_02_3, //passiveobject/creature/chn_shelby/shelbypink/animation/09_shelbypink_overskill_body.ani
        SHELBYRED_SKILL_02_4, //passiveobject/creature/chn_shelby/shelbyred/animation/09_shelbyred_overskill_body.ani
        CANFAIRY_LASER, //passiveobject/creature/launchergirl/animation/launchergirl_blue_skill_laser1.ani
        REVA_SM_DROP, //passiveobject/creature/reva/soul_effect_skill.ani
        REVA_SM_CRASH, //passiveobject/creature/reva/soul_skill.ani
        THUNDERC_LIGHTNING, //passiveobject/event/bluemarble/animation/magelighthigherspiritthunder2.ani
        R_CASILLAS_DROP, //passiveobject/monster/casillas/animation/swordrain/slantnormal1.ani
        R_CASILLAS_STICK, //passiveobject/monster/casillas/animation/swordrain/slantnormal2.ani
        POWERGRAB_INCOUNT_ATTACK, //ui/assault/lightningeffect.ani
        BLUEMARBLE_MOVE, //ui/bluemarble/animation/board/00_eventmap_move_01_01.ani
        BLUEMARBLE_BONUS, //ui/bluemarble/animation/buff/00_eventmap_buff02_back.ani
        COUNT_DOWN, //ui/bluemarble/animation/countdown/eventmap_countdown_5start.ani
        DICE_RESULT, //ui/bluemarble/animation/dice/eventmap_dice_00.ani
        TWINRAID_COUNT_5, //ui/dualraid/countdown/eventmap_countdown_5_1.ani
        TWINRAID_GAUGE_01, //ui/dualraid/ingameui/boss_change.ani
        TRANSUI_FLASH, //ui/event/ontimeevent/ontimeevent4rd/ontime_event_infomation_00.ani
        TIMEPIECE_CREATE, //ui/quest/animation/gear_slot_effect.ani
        LICKSYS_ON, //ui/selectcharacter/link_system/link02_a02.ani
        LICKSYS_OFF, //ui/selectcharacter/link_system/link02_a04.ani
        SKILL_LEARN, //ui/skill/animation/new_notice_effect/skill_new_notice01.ani
        BOX_SHAKE, //ui/tournament/animation/suju_matching_loading_02.ani
        MARBLE, //ui/tournament/animation/suju_matching_loading_04.ani
        MON_FAIL, //ui/tournament/animation/suju_matching_lose.ani
        BATTLE_VICTORY, //ui/tournament/animation/suju_matching_victory02.ani
        READY_FEVOICE, //ui/tournament/animation/suju_pve_ready02.ani
        FIGHT_FEVOICE, //ui/tournament/animation/suju_pve_ready03.ani
        GATE_OPEN, //ui/tournament/animation/suju_pve_starteff_02.ani
        VICTORY_CHEER, //ui/tournament/animation/suju_pve_win02.ani
        NENSU_INVOKE, //aicharacter/atfighter/karsh/animation/nenflower.ani
        MF_NET, //aicharacter/atfighter/randas/animation/throwweb.ani
        TELEPORT_ACT_02, //character/common/animation/teleport/after/teleportend_circle01.ani
        FT_BLOCKBUSTER, //character/fighter/animation/blockbusterexfinish.ani
        R_FT_KICK_AX, //character/fighter/animation/groundkickkick.ani
        STRONG_LOWKICK_READY, //character/fighter/animation/strongestlowkickstamp.ani
        GC_03, //character/fighter/atanimation/108stairsexblow.ani
        A_EYE_FRASH, //character/fighter/atanimation/108stairsexfinal.ani
        PFRUIT_THROW, //character/fighter/atanimation/108stairsexthrow.ani
        MF_4ATK, //character/fighter/atanimation/attack4.ani
        MSPIRE_KICK, //character/fighter/atanimation/closepunch.ani
        CRAZYWHIP_ATK, //character/fighter/atanimation/crashrope.ani
        CBOONG_TURN_STONE, //character/fighter/atanimation/destroyearthskydroponsky.ani
        CBOONG_CHAIN_PULL, //character/fighter/atanimation/destroyearthskydropstart.ani
        MFIRE_CHANGE, //character/fighter/atanimation/flamelegscast.ani
        R_MF_THROW, //character/fighter/atanimation/glueyfruitthrow.ani
        MF_POWDER, //character/fighter/atanimation/grabexplosionkick.ani
        HSPEAR_HURRICANE, //character/fighter/atanimation/hurricanespear.ani
        LIGHTNING_EXP, //character/fighter/atanimation/jumpsupleximpressholdkick.ani
        NEN_TIGERATK_FIN, //character/fighter/atanimation/lightningdragon.ani
        NENSU_EXP_READY, //character/fighter/atanimation/nenflowerfinal.ani
        NHWAN_START, //character/fighter/atanimation/spiralcolumnex.ani
        SUPPER_HIT_02, //character/fighter/atanimation/suplexfinalattack.ani
        NET_OUT, //character/fighter/atanimation/throwwebdoublethrow.ani
        TYPHOON_FIN_DOWN, //character/fighter/effect/animation/typhoon/finish1.ani
        WZ_ARCTICF_02, //character/mage/animation/fusionchaser.ani
        CRYSTALATK_FALL, //character/mage/atanimation/crystalattack.ani
        ERAIN_SHOT, //character/mage/atanimation/elementalrainchargeshoot.ani
        MW_FLAMECILCLE_READY, //character/mage/atanimation/flamecircle1.ani
        MW_KSULHWA, //character/mage/atanimation/holonglight.ani
        MW_RAGEBLAST, //character/mage/atanimation/icechakram6.ani
        ICEBLADE_ATK_01, //character/mage/atanimation/icesword.ani
        MW_LIGHTWALL, //character/mage/atanimation/lightningwall.ani
        R_ICEAREA_FALL, //character/mage/atanimation/pieceofice.ani
        MW_KNAJANG, //character/mage/atanimation/push.ani
        KMYUNG_EXP, //character/mage/atanimation/resonance.ani
        WCANNON_SHOT, //character/mage/atanimation/watercannon.ani
        WINDSTRIKE, //character/mage/atanimation/windstrike.ani
        P_MAGESWING_DARK, //character/mage/effect/animation/swingex/dark_normal.ani
        PR_DGUARDIAN_1ATK, //character/priest/animation/avengerawakening/attack1.ani
        PR_DGUARDIAN_2ATK, //character/priest/animation/avengerawakening/attack2.ani
        PR_DGUARDIAN_3ATK, //character/priest/animation/avengerawakening/attack3.ani
        PR_DGUARDIAN_BUKMA, //character/priest/animation/avengerawakening/pandemoniumstart.ani
        DGUARDIAN_CHANGE_3, //character/priest/animation/awakening4.ani
        EARTHQUAKE_CRASH, //character/priest/animation/earthquake.ani
        EXECUTION_EXP_1, //character/priest/animation/execution/last.ani
        PR_HCOMBI_LEFT, //character/priest/animation/heavenlycombination.ani
        R_PR_ATK_03, //character/priest/animation/heavenlycombinationex.ani
        HEDGEHOG_BKNIFE, //character/priest/animation/hedgehog.ani
        PR_WEAPONATK_FIN, //character/priest/animation/machinegunjabexfinish.ani
        DGUARDIAN_CATCH, //character/priest/animation/ripper.ani
        SCUTTER_THROW, //character/priest/animation/spincutter1.ani
        BIGPUNCH_4SWING_READY, //character/priest/effect/animation/bigbangpunch/punch3.ani
        PHAMMER_CRASH, //character/priest/effect/animation/hammerofcontrition/hammer1.ani
        P_STRIKE, //character/swordman/dsanimation/flowmindone.ani
        TRIPLE_STEP_12, //character/swordman/dsanimation/triplestab.ani
        MYBLOOD, //character/thief/animation/darkritual.ani
        R_TF_FIREATK, //character/thief/animation/flamecut.ani
        SILVER_SATK4, //character/thief/animation/silverstreamfinishslash.ani
        RIDER_COUNT_GO, //common/etc/animation/eventmap_countdown_3start.ani
        PANDA_BUFF_BLUE, //creature/bluepanda/animation/skill.ani
        BONNYBUNNY_SPIN, //creature/bonnybunny/animation/tokki_skill2_01.ani
        ASHCORE_CRE_SKILL, //creature/petit_ashcore/skill/effect/petit_ashcore_effect_1_front.ani
        ITRENOG_SHOUT_READY, //creature/petit_itrenog/skill/effect/petit_itrenog_skill_start_front.ani
        NAGOR_CRE_CAST, //creature/petit_nagor/skill/effect/petit_nagor_skill_start_normal.ani
        PRINCESSPETIT_SKILL_03, //creature/princess_petit/animation/princess_skill_eff_a.ani
        REVA_PR_CRASH, //creature/reva/crusader/skill.ani
        ASUNA_CRE_SKILL_02, //creature/sao/asuna/animation/asuna_skill_normal.ani
        RIFA_CRE_LOOP_04, //creature/sao/suguha/animation/random.ani
        RIFA_CRE_LOOP_02, //creature/sao/suguha/animation/random01.ani
        REVA_PR_DISA, //creature/sdcharacter/priest/c_prist_skill.ani
        THUNDERC_ATK, //monster/newmonsters/thief/nicolas/animation/casting1.ani
        NI_DARKWAVE_GET, //monster/newmonsters/thief/nicolas/animation/casting2.[pvp].ani
        NI_BOOK, //monster/newmonsters/thief/nicolas/animation/casting3.ani
        NI_BLACKWEB_HAND, //monster/newmonsters/thief/nicolas/animation/casting4.ani
        DMURKER_DISAPPEAR_02, //monster/spirit/magedarkhigheranimation/die.ani
        LIGHTWALL_LOOP, //passiveobject/character/mage/animation/atlightningwall/createlightningwallbase.ani
        ICEPLATE_BREAK, //passiveobject/character/mage/animation/creatoriceplate/iceplate_ice_plate.ani
        SHIKIGAMI_BIGBIRD_ATK, //passiveobject/character/priest/animation/shikigami/expbird1.ani
        S_BLASHU_OUT, //passiveobject/character/swordman/animation/blache/body1.ani
        A_WHEEL, //passiveobject/character/swordman/animation/waveeye/wheelappear.ani
        TWINRAID_COUNT_4, //ui/dualraid/countdown/eventmap_countdown_5_1.ani
        TWINRAID_GAUGE_02, //ui/dualraid/ingameui/boss_change.ani
        TELEPORT_ACT_03, //character/common/animation/teleport/after/teleportend_circle01.ani
        SCYCLONE_CRASH, //character/fighter/animation/strongestlowkickstamp.ani
        GC_012, //character/fighter/atanimation/108stairsexblow.ani
        MF_BDRIVE_FIN, //character/fighter/atanimation/108stairsexfinal.ani
        DOUBLEP_KICK_02, //character/fighter/atanimation/hurricanespear.ani
        LAMPLIGHT_CREATE, //character/mage/atanimation/holonglight.ani
        MW_ICEBLADE_2ATK, //character/mage/atanimation/icesword.ani
        MW_WCANNON, //character/mage/atanimation/watercannon.ani
        PR_DGUARDIAN_END, //character/priest/animation/awakening4.ani
        PR_HCOMBI_FIN, //character/priest/animation/heavenlycombination.ani
        PHAMMER_DISAP, //character/priest/effect/animation/hammerofcontrition/hammer1.ani
        TRIPLE_STEP_3, //character/swordman/dsanimation/triplestab.ani
        BONNYBUNNY_COINATK, //creature/bonnybunny/animation/tokki_skill2_01.ani
        ASUNA_CRE_SKILL_03, //creature/sao/asuna/animation/asuna_skill_normal.ani
        RIFA_CRE_LOOP_05, //creature/sao/suguha/animation/random.ani
        NI_BLACKWEB, //monster/newmonsters/thief/nicolas/animation/casting4.ani
        TWINRAID_COUNT_3, //ui/dualraid/countdown/eventmap_countdown_5_1.ani
        TWINRAID_GAUGE_03, //ui/dualraid/ingameui/boss_change.ani
        ICEBLADE_ATK_02, //character/mage/atanimation/icesword.ani
        RIFA_CRE_LOOP_06, //creature/sao/suguha/animation/random.ani
        TWINRAID_COUNT_2, //ui/dualraid/countdown/eventmap_countdown_5_1.ani
        R_MW_ICEBLADE_3ATK, //character/mage/atanimation/icesword.ani
        TWINRAID_COUNT_1, //ui/dualraid/countdown/eventmap_countdown_5_1.ani
    }
}